[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."send-email"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/reservas"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contacto"
  to = "/index.html"
  status = 200
